#!/usr/bin/env bash
set -euxo pipefail

# Usage:
#   ./create-release.sh <mod_version>
#
# Example:
#   ./create-release.sh latest
#

MOD_VERSION="$1"

VCMI_COMPAT=$(jq -r '.compatibility.min' mmai/mod.json)
RELEASE_TAG="vcmi-${VCMI_COMPAT}-${MOD_VERSION}"
REPO="${GITHUB_REPOSITORY}"

cat <<-EOF
Vars:
    GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}
    MOD_VERSION: ${MOD_VERSION}
    VCMI_COMPAT: ${VCMI_COMPAT}
    RELEASE_TAG: ${RELEASE_TAG}
    GITHUB_SHA: ${GITHUB_SHA}
EOF

##############################################################################
# Rename release RELEASE_TAG (if exists)
##############################################################################

if gh release view "${RELEASE_TAG}" -R "${REPO}"; then
    echo "Release with tag ${RELEASE_TAG} exists, will rename it."

    # Get publish date (ISO 8601) of the existing release
    PUBLISHED_AT="$(gh release view "${RELEASE_TAG}" -R "${REPO}" --json publishedAt -q '.publishedAt')"

    if [ -z "${PUBLISHED_AT}" ] || [ "${PUBLISHED_AT}" = "null" ]; then
        echo "Error: existing release has no publishedAt; cannot compute date tag."
        exit 1
    fi

    # Construct new tag for the old release (replace "latest" with the publish date)
    PUBLISHED_TIMESTAMP="$(date -d "${PUBLISHED_AT}" +%Y%m%d%H%M%S)"
    NEW_TAG="${RELEASE_TAG/latest/${PUBLISHED_TIMESTAMP}}"

    if gh release view "${NEW_TAG}" --repo "${REPO}"; then
        echo "Error: a release with tag ${NEW_TAG} already exists. Aborting."
        exit 1
    fi

    # notes=$(command gh release view "${RELEASE_TAG}" --json body --jq .body)
    # new_notes=$(printf "%s\n*Outdated:* %s" "$old_notes" "$(date '+%F %T')")

    # Rename the release
    gh release edit "${RELEASE_TAG}" \
        --repo "${REPO}" \
        --tag "${NEW_TAG}" \
        --title "${NEW_TAG}"
fi

##############################################################################
### Download models
##############################################################################

settings=$(jq '.models = {}' mmai/config/mmai-settings.json)

while read -r name url; do
  filename="${url##*/}"
  curl --fail -Lo "mmai/models/${filename}" "${url}"
  settings=$(echo "$settings" | jq --arg k "$name" --arg v "$filename" '.models[$k] = $v')
done < <(jq -r 'to_entries[] | "\(.key) \(.value)"' mmai/models/sources.json)

echo "$settings" > 'mmai/config/mmai-settings.json'

##############################################################################
# Create new release with RELEASE_TAG from current HEAD
##############################################################################

notes=$(cat <<EOF
Generated by GHA run [${GITHUB_RUN_ID}](https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID})
EOF
)

gh release create "${RELEASE_TAG}" \
    --repo "${REPO}" \
    --target "${GITHUB_SHA}" \
    --title "${RELEASE_TAG}" \
    --notes "${notes}"

files=(mmai/mod.json)

zip -qr vcmi-mod.zip mmai

files+=(vcmi-mod.zip)


for f in screenshots/*.png; do
    [ -f "$f" ] || continue  # handle literal '*' if expansion failed
    files+=("$f")
done

gh release upload "${RELEASE_TAG}" "${files[@]}" --repo "${REPO}"
